name: hth
description: An app that allows users who face problems with their mental well-being to chat with professionals.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  url_launcher: ^5.4.0
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: IndieFlower
    fonts:
      - asset: fonts/IndieFlower-Regular.ttf

  - family: Arapey
    fonts:
      - asset: fonts/Arapey-Italic.ttf
      - asset: fonts/Arapey-Regular.ttf

  - family: Phone_24h
    fonts:
      - asset: icons/Phone_24h.ttf
